# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XMtool(object):
    def setupUi(self, XMtool):
        XMtool.setObjectName("XMtool")
        XMtool.resize(701, 622)
        self.verticalLayout = QtWidgets.QVBoxLayout(XMtool)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox_2 = QtWidgets.QGroupBox(XMtool)
        self.formGroupBox_2.setObjectName("formGroupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.formGroupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_18 = QtWidgets.QLabel(self.formGroupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.formGroupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.formGroupBox_2)
        self.frame.setObjectName("frame")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.r1r = QtWidgets.QLineEdit(self.frame)
        self.r1r.setObjectName("r1r")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.r1r)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.r1z = QtWidgets.QLineEdit(self.frame)
        self.r1z.setObjectName("r1z")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.r1z)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.r1y = QtWidgets.QLineEdit(self.frame)
        self.r1y.setObjectName("r1y")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.r1y)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.r3y = QtWidgets.QLineEdit(self.frame)
        self.r3y.setObjectName("r3y")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.r3y)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.r6y = QtWidgets.QLineEdit(self.frame)
        self.r6y.setObjectName("r6y")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.r6y)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.r1n = QtWidgets.QLineEdit(self.frame)
        self.r1n.setObjectName("r1n")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.r1n)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.r2n = QtWidgets.QLineEdit(self.frame)
        self.r2n.setObjectName("r2n")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.r2n)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.r3n = QtWidgets.QLineEdit(self.frame)
        self.r3n.setObjectName("r3n")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.r3n)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.rjnl = QtWidgets.QLineEdit(self.frame)
        self.rjnl.setObjectName("rjnl")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.rjnl)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.rcll = QtWidgets.QLineEdit(self.frame)
        self.rcll.setObjectName("rcll")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.rcll)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.formGroupBox_2)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(18, 18, 96, 24))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(18, 61, 96, 24))
        self.label_12.setObjectName("label_12")
        self.sc = QtWidgets.QComboBox(self.frame_2)
        self.sc.setGeometry(QtCore.QRect(126, 61, 91, 30))
        self.sc.setObjectName("sc")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.addItem("")
        self.sc.setItemText(15, "")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(18, 103, 96, 24))
        self.label_13.setObjectName("label_13")
        self.st = QtWidgets.QComboBox(self.frame_2)
        self.st.setGeometry(QtCore.QRect(126, 103, 90, 30))
        self.st.setObjectName("st")
        self.st.addItem("")
        self.st.addItem("")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(18, 145, 96, 24))
        self.label_14.setObjectName("label_14")
        self.ft = QtWidgets.QComboBox(self.frame_2)
        self.ft.setGeometry(QtCore.QRect(126, 145, 90, 30))
        self.ft.setObjectName("ft")
        self.ft.addItem("")
        self.ft.addItem("")
        self.ft.addItem("")
        self.ft.addItem("")
        self.ft.addItem("")
        self.ft.addItem("")
        self.ft.addItem("")
        self.ft.addItem("")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(18, 187, 96, 24))
        self.label_15.setObjectName("label_15")
        self.dx = QtWidgets.QComboBox(self.frame_2)
        self.dx.setGeometry(QtCore.QRect(126, 187, 55, 30))
        self.dx.setObjectName("dx")
        self.dx.addItem("")
        self.dx.addItem("")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(18, 229, 96, 24))
        self.label_16.setObjectName("label_16")
        self.season = QtWidgets.QComboBox(self.frame_2)
        self.season.setGeometry(QtCore.QRect(126, 229, 56, 30))
        self.season.setObjectName("season")
        self.season.addItem("")
        self.season.addItem("")
        self.season.addItem("")
        self.season.addItem("")
        self.sample = QtWidgets.QLineEdit(self.frame_2)
        self.sample.setGeometry(QtCore.QRect(126, 18, 151, 30))
        self.sample.setObjectName("sample")
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.formGroupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 1, 1, 1)
        self.frame.raise_()
        self.frame_2.raise_()
        self.label_18.raise_()
        self.label_17.raise_()
        self.pushButton.raise_()
        self.verticalLayout.addWidget(self.formGroupBox_2)

        self.retranslateUi(XMtool)
        self.pushButton.clicked.connect(XMtool.accept)
        QtCore.QMetaObject.connectSlotsByName(XMtool)

    def retranslateUi(self, XMtool):
        _translate = QtCore.QCoreApplication.translate
        XMtool.setWindowTitle(_translate("XMtool", "Dialog"))
        XMtool.setToolTip(_translate("XMtool", "<html><head/><body><p>欢迎使用小明选股软件！</p></body></html>"))
        XMtool.setWhatsThis(_translate("XMtool", "<html><head/><body><p>不认识爸爸？</p></body></html>"))
        self.label_18.setText(_translate("XMtool", "基金数据参数设定："))
        self.pushButton.setText(_translate("XMtool", "小明已确定"))
        self.label.setText(_translate("XMtool", "日增长率"))
        self.r1r.setText(_translate("XMtool", "1"))
        self.label_2.setText(_translate("XMtool", "近1周"))
        self.r1z.setText(_translate("XMtool", "1"))
        self.label_3.setText(_translate("XMtool", "近1月"))
        self.r1y.setText(_translate("XMtool", "1"))
        self.label_4.setText(_translate("XMtool", "近3月"))
        self.r3y.setText(_translate("XMtool", "0.33333"))
        self.label_5.setText(_translate("XMtool", "近6月"))
        self.r6y.setText(_translate("XMtool", "0.33333"))
        self.label_6.setText(_translate("XMtool", "近1年"))
        self.r1n.setText(_translate("XMtool", "0.25"))
        self.label_7.setText(_translate("XMtool", "近2年"))
        self.r2n.setText(_translate("XMtool", "0.25"))
        self.label_8.setText(_translate("XMtool", "近3年"))
        self.r3n.setText(_translate("XMtool", "0.25"))
        self.label_9.setText(_translate("XMtool", "今年来"))
        self.rjnl.setText(_translate("XMtool", "0.25"))
        self.label_10.setText(_translate("XMtool", "成立来"))
        self.rcll.setText(_translate("XMtool", "1"))
        self.label_11.setText(_translate("XMtool", "样本数量"))
        self.label_12.setText(_translate("XMtool", "排序键值"))
        self.sc.setItemText(0, _translate("XMtool", "6yzf"))
        self.sc.setItemText(1, _translate("XMtool", "dm"))
        self.sc.setItemText(2, _translate("XMtool", "jc"))
        self.sc.setItemText(3, _translate("XMtool", "jzrq"))
        self.sc.setItemText(4, _translate("XMtool", "dwjz"))
        self.sc.setItemText(5, _translate("XMtool", "ljjz"))
        self.sc.setItemText(6, _translate("XMtool", "rzdf"))
        self.sc.setItemText(7, _translate("XMtool", "zzf"))
        self.sc.setItemText(8, _translate("XMtool", "1yzf"))
        self.sc.setItemText(9, _translate("XMtool", "3yzf"))
        self.sc.setItemText(10, _translate("XMtool", "1nzf"))
        self.sc.setItemText(11, _translate("XMtool", "2nzf"))
        self.sc.setItemText(12, _translate("XMtool", "3nzf"))
        self.sc.setItemText(13, _translate("XMtool", "jnzf"))
        self.sc.setItemText(14, _translate("XMtool", "lnzf"))
        self.label_13.setText(_translate("XMtool", "排序方式"))
        self.st.setItemText(0, _translate("XMtool", "desc"))
        self.st.setItemText(1, _translate("XMtool", "asc"))
        self.label_14.setText(_translate("XMtool", "基金类型"))
        self.ft.setItemText(0, _translate("XMtool", "all"))
        self.ft.setItemText(1, _translate("XMtool", "gp"))
        self.ft.setItemText(2, _translate("XMtool", "hh"))
        self.ft.setItemText(3, _translate("XMtool", "zs"))
        self.ft.setItemText(4, _translate("XMtool", "qdii"))
        self.ft.setItemText(5, _translate("XMtool", "zq"))
        self.ft.setItemText(6, _translate("XMtool", "lof"))
        self.ft.setItemText(7, _translate("XMtool", "fof"))
        self.label_15.setText(_translate("XMtool", "是否可购"))
        self.dx.setItemText(0, _translate("XMtool", "1"))
        self.dx.setItemText(1, _translate("XMtool", "0"))
        self.label_16.setText(_translate("XMtool", "季度选择"))
        self.season.setItemText(0, _translate("XMtool", "1"))
        self.season.setItemText(1, _translate("XMtool", "2"))
        self.season.setItemText(2, _translate("XMtool", "3"))
        self.season.setItemText(3, _translate("XMtool", "4"))
        self.sample.setText(_translate("XMtool", "15000"))
        self.label_17.setText(_translate("XMtool", "四四三三法则参数："))

